### ISSUE TITLE
Feedback Milestone 2

### ISSUE THREAD

**Issue by SuzanaMomo** [data301-2021-summer2/project-group02_project#2]
Hello, 

My name is _Suzana___ and I will be giving you some feedback on your project. 

Overall, the project  is a good starting point, but there is some work that needs to be done to elevate this project to our standards so its meets our expectations. The project seems to be all over the place and not very clear.

I have divided up the feedback into several sections so it is easier for you to implement.

## Task 1

- [x]  I did not find a proper analysis pipeline to load, clean, process, and wrangle the data for each of the students in a Jupyter Notebook. data cleaning was there but not the others

## Task 2

- [x] Could not find any functional method chaining. please make sure your method chain(s) reside in a .py file in the scripts directory.
- [x] Try to have some sort of indicator for separate tasks so that it is easier for me to identify individual tasks 

## Task 3

- [x] Your plots need to be more clear, i.e with proper legends, labels, explanation. The purpose of the plots were unclear to me 

## Task 4

- [x] Your plots and explanation of the research questions should be in one file not separate as it gets very difficult to relate your explanation with the plots since I can't see them simultaneously. 
- [x] Organize your tasks. Each research question (statement) then their plots (visualization) and then its explanation. Maintain this serial for every research question. 
- [x] Along with the existing plots try have another type of plots that might better visualize your research questions
- [x] The visualizations that you put is not clear and convincing enough to answer your research questions properly 
- [x] Andrew and Darren research questions seemed the same to me. please make a clear distinction between these two research questions  in the next milestone.
